apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
  namespace: $NAMESPACE
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      labels:
        app: $PROJECT_NAME
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: $CONFIG_MAP
        - secretRef:
            name: $SECRET_REF
      - name: $PROJECT_NAME
        image: $DOCKER_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
