apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_NAME
  namespace: $NAMESPACE
spec:
  selector:
    app: $PROJECT_NAME
  type: NodePort
  ports:
    - nodePort: $NODEPORT
      protocol: TCP
      port: 80
      targetPort: 80
